<?php
/************************************************************************/

/* This program is free software; you can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation; either version 2 of the License.       */
/*                                                                      */
/* This program is distributed in the hope that it will be useful, but  */
/* WITHOUT ANY WARRANTY; without even the implied warranty of           */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU     */
/* General Public License for more details.                             */
/*                                                                      */
/* You should have received a copy of the GNU General Public License    */
/* along with this program; if not, write to the Free Software          */
/* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  */
/* USA                                                                  */
/************************************************************************/

$modversion['name'] = 'Jinzora';
$modversion['version'] = '1.30';
$modversion['description'] = 'Media Manager';
$modversion['author'] = "<a href='mailto:admin@csmapcentral.com'>Jon Langevin aka bd_csmc aka intel352</a>";
$modversion['credits'] = 'Based on Jinzora v1.01 CVS.<br>Ported to Xoops2 with enhancements/fixes by <a href=http://www.csmapcentral.com>CSMapCentral.com</a><br>Xoops2 port maintained by bd_csmc.';
$modversion['help'] = '';
$modversion['license'] = 'GNU General Public License (GPL)';
$modversion['official'] = 0;
$modversion['image'] = '';
$modversion['dirname'] = 'xjinzora';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
//$modversion['sqlfile']['mysql'] = "sql/hlstats.sql";

// Tables created by sql file (without prefix!)
#$modversion['tables'][0] = "";

// Admin things
#$modversion['hasAdmin'] = 1;
#$modversion['adminindex'] = "admin/index.php";
//$modversion['adminmenu'] = "admin/menu.php";

// Blocks
/*$modversion['blocks'][1]['file'] = "Donat_o_Meter.php";
$modversion['blocks'][1]['name'] = "Donat_o_Meter";
$modversion['blocks'][1]['description'] = "Donations Block";
$modversion['blocks'][1]['show_func'] = "b_donations_donatometer_show";
$modversion['blocks'][1]['template'] = 'donations_donatometer.html';*/

// Menu
$modversion['hasMain'] = 1;
//$modversion['sub'][1]['name'] = 'Counter-Strike';
//$modversion['sub'][1]['url'] = 'index.php?game=cstrike';

// Templates
/*$modversion['templates'][1]['file'] = 'donations_main.html';
$modversion['templates'][1]['description'] = 'Donations Main Template';*/
