<input type="hidden" name="web_root" value="<?php echo str_replace('\\\\', '\\', $_POST['web_root']); ?>">
<input type="hidden" name="root_dir" value="<?php echo $_POST['root_dir']; ?>">
<input type="hidden" name="media_dir" value="<?php echo $_POST['media_dir']; ?>">
<input type="hidden" name="default_access" value="<?php echo $_POST['default_access']; ?>">
<input type="hidden" name="lang_file" value="<?php echo $_POST['lang_file']; ?>">
<input type="hidden" name="allow_lang_choice" value="<?php echo $_POST['allow_lang_choice']; ?>">
<input type="hidden" name="jinzora_skin" value="<?php echo $_POST['jinzora_skin']; ?>">
<input type="hidden" name="allow_theme_change" value="<?php echo $_POST['allow_theme_change']; ?>">
<input type="hidden" name="allow_download" value="<?php echo $_POST['allow_download']; ?>">
<input type="hidden" name="get_mp3_info" value="<?php echo $_POST['get_mp3_info']; ?>">
<input type="hidden" name="hide_id3_comments" value="<?php echo $_POST['hide_id3_comments']; ?>">
<input type="hidden" name="playlist_dir" value="<?php echo $_POST['jinzora_temp_dir']; ?>">
<input type="hidden" name="playlist_ext" value="<?php echo $_POST['playlist_ext']; ?>">
<input type="hidden" name="jinzora_temp_dir" value="<?php echo $_POST['jinzora_temp_dir']; ?>">
<input type="hidden" name="playlist_directory" value="<?php echo $_POST['jinzora_temp_dir']; ?>">
<input type="hidden" name="directory_level" value="<?php echo $_POST['directory_level']; ?>">
<input type="hidden" name="show_loggedin_level" value="<?php echo $_POST['show_loggedin_level']; ?>">
<input type="hidden" name="cols_in_genre" value="<?php echo $_POST['cols_in_genre']; ?>">
<input type="hidden" name="cellspacing" value="<?php echo $_POST['cellspacing']; ?>">
<input type="hidden" name="song_cellpadding" value="<?php echo $_POST['song_cellpadding']; ?>">
<input type="hidden" name="artist_truncate" value="<?php echo $_POST['artist_truncate']; ?>">
<input type="hidden" name="quick_list_truncate" value="<?php echo $_POST['quick_list_truncate']; ?>">
<input type="hidden" name="album_name_truncate" value="<?php echo $_POST['album_name_truncate']; ?>">
<input type="hidden" name="main_table_width" value="<?php echo $_POST['main_table_width']; ?>">
<input type="hidden" name="random_play_amounts" value="<?php echo $_POST['random_play_amounts']; ?>">
<input type="hidden" name="random_play_types" value="<?php echo $_POST['random_play_types']; ?>">
<input type="hidden" name="audio_types" value="<?php echo $_POST['audio_types']; ?>">
<input type="hidden" name="video_types" value="<?php echo $_POST['video_types']; ?>">
<input type="hidden" name="ext_graphic" value="<?php echo $_POST['ext_graphic']; ?>">
<input type="hidden" name="track_num_seperator" value="<?php echo $_POST['track_num_seperator']; ?>">
<input type="hidden" name="ephPod_file_name" value="<?php echo $_POST['ephPod_file_name']; ?>">
<input type="hidden" name="ephPod_drive_letter" value="<?php echo $_POST['ephPod_drive_letter']; ?>">
<input type="hidden" name="ipod_size" value="<?php echo $_POST['ipod_size']; ?>">
<input type="hidden" name="javascript" value="<?php echo $_POST['javascript']; ?>">
<input type="hidden" name="header_drops" value="<?php echo $_POST['header_drops']; ?>">
<input type="hidden" name="start_page" value="<?php echo $_POST['start_page']; ?>">
<input type="hidden" name="num_other_albums" value="<?php echo $_POST['num_other_albums']; ?>">
<input type="hidden" name="genre_drop" value="<?php echo $_POST['genre_drop']; ?>">
<input type="hidden" name="artist_drop" value="<?php echo $_POST['artist_drop']; ?>">
<input type="hidden" name="album_drop" value="<?php echo $_POST['album_drop']; ?>">
<input type="hidden" name="song_drop" value="<?php echo $_POST['song_drop']; ?>">
<input type="hidden" name="quick_drop" value="<?php echo $_POST['quick_drop']; ?>">
<input type="hidden" name="album_img_width" value="<?php echo $_POST['album_img_width']; ?>">
<input type="hidden" name="album_img_height" value="<?php echo $_POST['album_img_height']; ?>">
<input type="hidden" name="album_force_width" value="<?php echo $_POST['album_force_width']; ?>">
<input type="hidden" name="album_force_height" value="<?php echo $_POST['album_force_height']; ?>">
<input type="hidden" name="artist_img_width" value="<?php echo $_POST['artist_img_width']; ?>">
<input type="hidden" name="artist_img_height" value="<?php echo $_POST['artist_img_height']; ?>">
<input type="hidden" name="keep_porportions" value="<?php echo $_POST['keep_porportions']; ?>">
<input type="hidden" name="search_album_art" value="<?php echo $_POST['search_album_art']; ?>">
<input type="hidden" name="sort_by_year" value="<?php echo $_POST['sort_by_year']; ?>">
<input type="hidden" name="amg_search" value="<?php echo $_POST['amg_search']; ?>">
<input type="hidden" name="hide_tracks" value="<?php echo $_POST['hide_tracks']; ?>">
<input type="hidden" name="shoutcast" value="<?php echo $_POST['shoutcast']; ?>">
<input type="hidden" name="sc_host" value="<?php echo $_POST['sc_host']; ?>">
<input type="hidden" name="sc_port" value="<?php echo $_POST['sc_port']; ?>">
<input type="hidden" name="sc_password" value="<?php echo $_POST['sc_password']; ?>">
<input type="hidden" name="sc_refresh" value="<?php echo $_POST['sc_refresh']; ?>">
<input type="hidden" name="auto_search_art" value="<?php echo $_POST['auto_search_art']; ?>">
<input type="hidden" name="show_sub_numbers" value="<?php echo $_POST['show_sub_numbers']; ?>">
<input type="hidden" name="download_mp3_only" value="<?php echo $_POST['download_mp3_only']; ?>">
<input type="hidden" name="embedded_header" value="<?php echo $_POST['embedded_header']; ?>">
<input type="hidden" name="embedded_footer" value="<?php echo $_POST['embedded_footer']; ?>">
<input type="hidden" name="show_tools_link" value="<?php echo $_POST['show_tools_link']; ?>">
<input type="hidden" name="auth_value" value="<?php echo $_POST['auth_value']; ?>">
<input type="hidden" name="admin_user" value="<?php echo $_POST['admin_user']; ?>">
<input type="hidden" name="adminpass" value="<?php echo $_POST['adminpass']; ?>">
<input type="hidden" name="show_all_checkboxes" value="<?php echo $_POST['show_all_checkboxes']; ?>">
<input type="hidden" name="num_rand_albums" value="<?php echo $_POST['num_rand_albums']; ?>">
<input type="hidden" name="use_cache_file" value="<?php echo $_POST['use_cache_file']; ?>">
<input type="hidden" name="cms_user_access" value="<?php echo $_POST['cms_user_access']; ?>">
<input type="hidden" name="help_access" value="<?php echo $_POST['help_access']; ?>">
<input type="hidden" name="enable_ratings" value="<?php echo $_POST['enable_ratings']; ?>">
<input type="hidden" name="num_top_ratings" value="<?php echo $_POST['num_top_ratings']; ?>">
<input type="hidden" name="num_suggestions" value="<?php echo $_POST['num_suggestions']; ?>">
<input type="hidden" name="enable_suggestions" value="<?php echo $_POST['enable_suggestions']; ?>">
<input type="hidden" name="track_plays" value="<?php echo $_POST['track_plays']; ?>">
<input type="hidden" name="enable_discussion" value="<?php echo $_POST['enable_discussion']; ?>">
<input type="hidden" name="display_time" value="<?php echo $_POST['display_time']; ?>">
<input type="hidden" name="display_rate" value="<?php echo $_POST['display_rate']; ?>">
<input type="hidden" name="display_feq" value="<?php echo $_POST['display_feq']; ?>">
<input type="hidden" name="display_size" value="<?php echo $_POST['display_size']; ?>">
<input type="hidden" name="days_for_new" value="<?php echo $_POST['days_for_new']; ?>">
<input type="hidden" name="enable_most_played" value="<?php echo $_POST['enable_most_played']; ?>">
<input type="hidden" name="num_most_played" value="<?php echo $_POST['num_most_played']; ?>">
<input type="hidden" name="jukebox" value="<?php echo $_POST['jukebox']; ?>">
<input type="hidden" name="auto_refresh" value="<?php echo $_POST['auto_refresh']; ?>">
<input type="hidden" name="num_upcoming" value="<?php echo $_POST['num_upcoming']; ?>">
<input type="hidden" name="rss_news_max" value="<?php echo $_POST['rss_news_max']; ?>">
<input type="hidden" name="cms_mode" value="<?php echo $_POST['cms_mode']; ?>">
<input type="hidden" name="cms_type" value="<?php echo $_POST['cms_type']; ?>">
<input type="hidden" name="download_speed" value="<?php echo $_POST['download_speed']; ?>">
<input type="hidden" name="multiple_download_mode" value="<?php echo $_POST['multiple_download_mode']; ?>">
<input type="hidden" name="single_download_mode" value="<?php echo $_POST['single_download_mode']; ?>">
<input type="hidden" name="date_format" value="<?php echo $_POST['date_format']; ?>">
<input type="hidden" name="echocloud" value="<?php echo $_POST['echocloud']; ?>">
<input type="hidden" name="disable_random" value="<?php echo $_POST['disable_random']; ?>">
<input type="hidden" name="info_level" value="<?php echo $_POST['info_level']; ?>">
<input type="hidden" name="auto_search_lyrics" value="<?php echo $_POST['auto_search_lyrics']; ?>">
<input type="hidden" name="track_play_only" value="<?php echo $_POST['track_play_only']; ?>">
<input type="hidden" name="enable_playlist" value="<?php echo $_POST['enable_playlist']; ?>">
<input type="hidden" name="display_downloads" value="<?php echo $_POST['display_downloads']; ?>">
<input type="hidden" name="display_track_num" value="<?php echo $_POST['display_track_num']; ?>">
